[package]
name = "reciprocity_communication"
version = "0.1.0"
authors = ["Autumnal <friedrich122112@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "^0"
futures = "^0"
thiserror = "^1"
serde = { version = "^1", features = ["derive"] }
serde_cbor = "0.11.1"
tokio-tungstenite = "^0"
tungstenite = "^0"
tokio-stream = "^0"
serenity = "^0"

tokio = { version = "^1", features = ["rt-multi-thread", "time", "sync", "net"] }